version: '3.7'

services:
    php:
        image: telesoftas/php:8.1
        volumes:
            -   ./app:/srv/app
    nginx:
        image: nginx:latest
        volumes:
            -  ./app:/srv/app
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
